language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  pip install cython &&
  pip install -r requirements.txt &&
  pip install .
# command to run tests
script: "py.test tests/"
