language: python
python:
  - "2.7"
# command to install dependencies
install:
  pip install cython &&
  pip install -r requirements.txt &&
  python setup.py build_ext --inplace
# command to run tests
script: "py.test tests/"
